url: http://www.citizenscode.org
baseurl: 

# Site settings
title: Citizens Code
email: ryan.brideau@gmail.com
description: "Citizens Code is a creative outlet for technical citizens. We work with open data to advance public policy, raise the level of civic dialog, and to improve our cities."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 28569a
  secondary: 21477F
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/orgs/CitizensCode
  - title: twitter
    url: http://twitter.com/citizenscode
  #- title: facebook
  #  url: https://www.facebook.com/CitizensCodeOrg

# Postal address (add as many lines as necessary)
address:
  - line: 469 King Street
  - line: Fredericton, NB, Canada
  - line: E3B 1E5

# Build settings
markdown: kramdown
permalink: pretty